name: "Fast Deploy"
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - README.md
      - LICENSE
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true  # 缓存，超级加速

      - name: Build site
        run: bundle exec jekyll b -d _site
        env:
          JEKYLL_ENV: production

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  # 极速同步到服务器
  sync-to-server:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./_site

      - name: Sync to server
        uses: burnett01/rsync-deployments@master
        with:
          switches: -avz --delete --quiet
          path: ./_site/
          remote_path: /home/ubuntu/blog
          remote_host: ${{ secrets.HOST }}
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_KEY }}